### ISSUE TITLE
When do the mission appear?

### ISSUE THREAD

**Issue by Zatana2021** [hythloday/VenturePlanSoDMissions#10]
I believe I have all the code in the right place and the addon is on the list with the original.
Just a question. I changed my Covenant a few days ago. I see no new missions from 9.1
I assume that I have to advance the covenant campaign progress to a certain level to see them?
Thanks for your time. :)

**Comment by hythloday** [comment]
I'm afraid I have no idea and this is nothing to do with the addon. Going to close this but if you do see a difference in the missions available with and without the addon, please let me know. :)
