### ISSUE TITLE
Spell [330] Oversight and [331] Supporting Fire have the wrong values in extra-vs-spells.lua

### ISSUE THREAD

**Issue by zealvurte** [hythloday/VenturePlanSoDMissions#11]
[330] Oversight targets all allies, not self (4), and the modifier is 20, not 25 (see https://wow.tools/dbc/?dbc=garrautospelleffect&build=9.1.0.39335&hotfixes=true#page=1&colFilter[1]=exact%3A330)
[331] Supporting Fire targets all other allies, not all allies, and the modifier is 20, not 23 (see https://wow.tools/dbc/?dbc=garrautospelleffect&build=9.1.0.39335&hotfixes=true#page=1&colFilter[1]=exact%3A331)

Therefore:
```lua
[330]={type="aura", target=4, duration=2, plusDamageDealtATK=25}, --Oversight
[331]={type="aura", target="all-allies", plusDamageDealtATK=23, duration=3}, --Supporting Fire (I'm not sure it needs duration 3)
```
should be:
```lua
[330]={type="aura", target="all-allies", duration=2, plusDamageDealtATK=20}, --Oversight
[331]={type="aura", target="all-other-allies", duration=3, plusDamageDealtATK=20}, --Supporting Fire
```
This data is accurate to the DBC values, and has been tested and verified against real logs.

N.b. that other issues present in various local functions and variables not accessible from T can still produce incorrect sims regardless of this correction, so correct spell data is only going to get you so far with accuracy.

**Comment by T0mate** [comment]
I can confirm the value proposed by @zealvurte are the which were present in the last "moded" version of VenturePlan which is not available anymore.
I have to other difference in the moded version those two spell:
`[346]={type="aura", target=0, duration=2, damageATK1=30, plusDamageDealtATK=1}, --Heel Bite (BUGGED: Should be modDamageDealt=-1. It isn't.)
[349]={type="nuke", target="all-enemies", damageATK=10}, --Anima Swell`
Can you confirm your values are correct ?

**Comment by zealvurte** [comment]
Your first set is accurate to the data, although:
- [344] The comment is incorrect, as it matches data and tooltip just fine (though variable wording is a tad misleading, as it would be better named `modDamageTakenATK`).
- [346] The comment is partially correct; the tooltip does suggest this should be a negative number, but it's not. The value is also tiny, which also seems to further suggest a mistake by Blizzard. It definitely is the ATK variant, `plusDamageDealtATK` though.

**Comment by LostTemple1990** [comment]
there are still sim errors caused by incorrect sim cast sequence,which can't be fix by modifing extra-vs-spells.lua.
@zealvurte  great thanks to your apply of the "last modified version" in git, I've found a easy way to check if the sim is match to the real log by adding another report when checkpoint is not match
however ,there are still some sim errors I found and I tried to fix it by myself
e.g. issue of cast sequence for healing spell that I fixed cause another problem
so i would like to create a new project in git "**without sourcecode**" to discuss about this
would you please to join the discussion later when you are not busy to help collect more data of sim?

**Comment by zealvurte** [comment]
Yesterday VenturePlan's author announced that someone has come forward to take it over and they will be making an announcement of their plans soon, so this probably isn't necessary anymore; however, if you still choose to go ahead, I'm happy to join the discussion.

Since that reporting functionality issue I posted, I've done a lot more work, fixed more inaccuracies, and verified more changes, and I'm over 200 missions done without inaccuracy now, but my testing is limited to one character (1 covenant, and limited mission set), so there's probably more I've yet to discover, and changes I can't verify myself.

**Comment by Psyshadow** [comment]
Oh wow! Would you mind directing me/anyone else who reads this to that announcement? I would appreciate it, and also very very much appreciate you putting this together in the meantime - I send all my missions out on 5 alts multiple times a day and the work you did here has already saved me a lot of time and spared me many failed missions so I really appreciate it!

**Comment by hythloday** [comment]
The announcement seems to be here:

https://discord.com/channels/327414731654692866/327414731654692866/867130651849261087

I'll keep maintaining this patching addon until the new maintainer releases a version that supersedes this.
