### ISSUE TITLE
Quests and companions where it's abilities aren't been taken into account

### ISSUE THREAD

**Issue by Thedrhunter** [hythloday/VenturePlanSoDMissions#15]
**Quests:**

https://www.wowhead.com/mission=2300/shirking-work
https://www.wowhead.com/mission=2301/learn-from-the-master
https://www.wowhead.com/mission=2302/strongarm-squad
https://www.wowhead.com/mission=2303/customary-shakedown
https://www.wowhead.com/mission=2304/a-few-too-many
https://www.wowhead.com/mission=2305/unexpected-delays
https://www.wowhead.com/mission=2306/bag-inspection
https://www.wowhead.com/mission=2307/piratical-problems
https://www.wowhead.com/mission=2308/nimble-scavengers
https://www.wowhead.com/mission=2309/full-stomachs
https://www.wowhead.com/mission=2310/sharp-hides-sharper-teeth
https://www.wowhead.com/mission=2311/on-wings-of-ferocity
https://www.wowhead.com/mission=2312/hunter-becomes-the-hunted
https://www.wowhead.com/mission=2313/gatecrashers
https://www.wowhead.com/mission=2314/legend-of-the-animaswell
https://www.wowhead.com/mission=2315/legend-of-the-animaswell
https://www.wowhead.com/mission=2316/legend-of-the-animaswell
https://www.wowhead.com/mission=2317/legend-of-the-animaswell

**New companions:**

https://www.wowhead.com/npc=179480/hermestes
https://www.wowhead.com/npc=179481/lyra-hailstorm
https://www.wowhead.com/npc=179482/chachi-the-artiste
https://www.wowhead.com/npc=179479/sulanoom
https://www.wowhead.com/npc=179488/cromas-the-mystic
https://www.wowhead.com/npc=179493/enceladus
https://www.wowhead.com/npc=179483/elwyn
https://www.wowhead.com/npc=179498/madame-iza
https://www.wowhead.com/npc=179489/auric-spiritguide
https://www.wowhead.com/npc=179494/deathfang
https://www.wowhead.com/npc=179484/yanlar
https://www.wowhead.com/npc=179499/lucia

Thanks for your efforts!

**Comment by siweia** [comment]
Mose of the quests have been taken into account. No idea why you come up with not.

**Comment by Thedrhunter** [comment]
> Most of the quests have been taken into account, or all. No idea why you come up with not.

Not all, the kyrian ones aren't.

**Comment by siweia** [comment]
> Not all, the kyrian ones aren't. I've received almost all these quests and the predict failed.

Did you use your new followers? They haven't been updated yet.

**Comment by Thedrhunter** [comment]
> And if you are kyrian, it seems normal to fail the quests, lol.

No, your statement is incorrect. So you don't need an addon, right?

> Did you use your new followers? They haven't been updated yet.

The first four are available, the others soon.

> If all the quests have not been taken into account, then they should predict as success.

The mob abilites aren't. The quest for sure are showing in the addon, but the maths are wrong because need to be added to the code.

And to end this discussion: Are you trying to solve the request or just make negative statements that guide to nowhere? Thanks.

**Comment by siweia** [comment]
If the mob abilities aren't included, the addon will try your enemy with no abilities. Then all your quest should predict as success.
Am I understood?

**Comment by hythloday** [comment]
Hi @Thedrhunter, I've definitely added some of these. What's this list from?

Both, keep it more civil please.

**Comment by Thedrhunter** [comment]
> Hi @Thedrhunter, I've definitely added some of these. What's this list from?

I've received mostly of these quests at my Command Table and these new quests are computing wrong because the abilities of the mobs, bosses are not computed in the account.

These new companions we receive through rewnown, same as above.

I started this thread in order to show what are new, in order to add it to your addon, not to show it's weakness or something else

**Comment by hythloday** [comment]
Oh yeah, no worries about that, if the addon is missing values I want to add them. I do appreciate you raising this (and I'm sorry it's not much of a fun first issue).

But for example, Legend of the Animaswell has only one NPC, who has the ability "Anima Swell", with spellID 349 - and as you can see it _should_ be accounted for: https://github.com/hythloday/VenturePlanSoDMissions/blob/main/extra-vs-spells.lua#L76

So I'm wondering how you're missing out on these. Are you running version 0.07?

**Comment by epiktetov** [comment]
@Thedrhunter: Actually, the VP add-on  does not include the list of missions and companions - the data about them can be queried in-game with API provided by Blizzard. However, this API only returns spell ID and there is no way to query what that spell does and how it works, this has to be reconstructed from in-game text description (and included into add-on)... which is often not clear enough and sometimes plain wrong.

@hythloday: Just FYI, from my experience (with version 0.07) most of the missions works fine, but not 100% yet. One of the mission with problems is "A few too many" that failed twice for me (Kyrian and NF), likely one of the enemy spell was not reconstructed correctly. Will try to investigate and would post corrections, if I find what's wrong.

Thank you!

**Comment by Thedrhunter** [comment]
> So I'm wondering how you're missing out on these. Are you running version 0.07

Yessir

**Comment by hythloday** [comment]
@Thedrhunter unfortunately, like @epiktetov explained, there's not a lot I can do with a list of missions or follower NPCs - going from those to spells takes a fair bit of data digging that I haven't been able to automate yet.

If you do find that you're getting missions mispredicted, the thing to do is to open an issue with the name of the _ability_ that the NPC uses. If you can also capture screenshots of the ability use that's even better.

Going to close this for now but I hope I'll be able to fix these with more data.
