### ISSUE TITLE
Please clarify how to use this? Put files in same or different directory?

### ISSUE THREAD

**Issue by Leebo-missile** [hythloday/VenturePlanSoDMissions#16]
After changing the LUA file, do we simply copy the folder to the interface/addon's directory or do we put the addon files within the same directory of the existing addon? 

Can you clarify installation instructions and file requirements.

**Comment by Leebo-missile** [comment]
![image](https://user-images.githubusercontent.com/54485295/126916906-c2875c67-dc73-4781-a40e-c480a773586f.png)
Will the text "this guide may be out of date disappear?"

**Comment by Jegethy** [comment]
Edit the Venture Plan vs.lua as shown then install this like any other addon by extracting it to C:\World of Warcraft\_retail_\Interface\AddOns (Drive letter may be different)

**Comment by Leebo-missile** [comment]
> Edit the Venture Plan vs.lua as shown then install this like any other addon by extracting it to C:\World of Warcraft_retail_\Interface\AddOns (Drive letter may be different)


Will the addon still show "this guide may be out of date" as seen in the above screenshot?

**Comment by Jegethy** [comment]
> > Edit the Venture Plan vs.lua as shown then install this like any other addon by extracting it to C:\World of Warcraft_retail_\Interface\AddOns (Drive letter may be different)
> 
> Will the addon still show "this guide may be out of date" as seen in the above screenshot?

Yes, it will.

**Comment by hythloday** [comment]
@Leebo-missile, I think Jegethy has sorted you out (thank you!), so going to close this.
