### ISSUE TITLE
personalization

### ISSUE THREAD

**Issue by N6REJ** [hythloday/VenturePlanSoDMissions#19]
@hythloday Hi.
First as a long time member of the FOSS community, ty for picking up the ball on this issue.
I currently have a email out to blizzards legal team on clarification of vp's right to have a closed copyright.
IN THE MEANTIME
I've renamed vp's folder to "BearsVenturePlan" and updated the toc accordingly.
The changed line #6 of your .toc to reflect that change 
"## Dependencies: BearsVenturePlan"
I don't see the addon in the "addons" list however.  Did I miss a change somewhere?

The reason for the change is to prevent it being overwritten by wowup in the future.
incase you doubt my integrity..  [https://github.com/N6REJ](https://github.com/N6REJ)

**Comment by N6REJ** [comment]
Here's what I see loaded..
![image](https://user-images.githubusercontent.com/1850089/127268769-e47d78b3-22af-4cdc-8ebb-00ae847a1b10.png)

**Comment by hythloday** [comment]
If you're going to rename the addon, it will change its registration in the _G table, and you'll also need to update [extra-spells.lua](https://github.com/hythloday/VenturePlanSoDMissions/blob/main/extra-vs-spells.lua). You might also want to install BugSack and BugGrabber to catch addon errors.

Going to close this as it's quite a bit outside the scope of what I want to support.
