### ISSUE TITLE
Missing Soul Cinders mission data

### ISSUE THREAD

**Issue by Psyshadow** [hythloday/VenturePlanSoDMissions#2]
Here's a mission that's missing. Sorry I dont know how to add it to the file myself but here are screenshots at least of it :)

thank you so much for making this!!! <3

![soulcinderswingsofferocity](https://user-images.githubusercontent.com/87551941/126019144-ea9b413c-660c-47b4-98f3-1c99187734de.png)
![soulcinderswingsofferocityfull](https://user-images.githubusercontent.com/87551941/126019177-c05d67d8-1c5b-41c2-8c14-6b7f39cf2842.png)

**Comment by hythloday** [comment]
Thanks! The external data the addon needs is actually spells, not missions, so this has now been fixed by #1. Look out for update 0.04.
