### ISSUE TITLE
New abilites from these new quests and followers

### ISSUE THREAD

**Issue by Thedrhunter** [hythloday/VenturePlanSoDMissions#20]
So you asked for prints, here are some:

![bag inspection](https://user-images.githubusercontent.com/87787112/127577202-581812aa-110e-442b-8c8f-b0e67317e0f1.png)
![customary shakedown](https://user-images.githubusercontent.com/87787112/127577216-b9d74d74-9594-4172-beb9-26e69dffc874.png)
![hunter becomes the hunted](https://user-images.githubusercontent.com/87787112/127577241-78f7624d-9c25-4860-8173-0c9c3ca52a43.png)
![learn from the master](https://user-images.githubusercontent.com/87787112/127577250-a7345346-ad42-4181-aaa5-cda61dbe2c87.png)
![legend of the animaswell](https://user-images.githubusercontent.com/87787112/127577257-e7d53e9f-317e-41f9-a401-d28655d1690b.png)
![sharp hides sharp teeth](https://user-images.githubusercontent.com/87787112/127577265-dca43320-0119-4eea-8e76-36ac504f60ed.png)
![shirking work](https://user-images.githubusercontent.com/87787112/127577273-2adabf40-d692-4182-88ec-4fb1720b8d86.png)
![strongarm squad](https://user-images.githubusercontent.com/87787112/127577281-b071bb32-5602-4d77-bac9-f142b4af1a49.png)
![unexpected delays](https://user-images.githubusercontent.com/87787112/127577292-72899110-74d1-46da-a78f-3c4fc30829ee.png)
![hermestes](https://user-images.githubusercontent.com/87787112/127577300-308738a3-134b-4fbb-b714-96cb2610e892.png)

As soon I get more, I'll attach here

**Comment by Thedrhunter** [comment]
![piratical problems](https://user-images.githubusercontent.com/87787112/127658065-b038d591-9641-4622-8c47-36883e86548f.png)

**Comment by hythloday** [comment]
I have only checked 4 of these, but they're all in the addon, e.g. https://github.com/hythloday/VenturePlanSoDMissions/blob/main/extra-vs-spells.lua#L55

**Comment by siweia** [comment]
There is no doubt that, all the missions have already included in the spell data.

**Comment by Thedrhunter** [comment]
@siweia take your trophy: https://bit.ly/3j6m76y and, give up, @hythloday  will not marry you.
