### ISSUE TITLE
Don't see addon loading

### ISSUE THREAD

**Issue by N6REJ** [hythloday/VenturePlanSoDMissions#21]
Per our last conversation I went back to default addon but I don't see your fix showing up?
What am I missing?
![image](https://user-images.githubusercontent.com/1850089/127599352-955049c2-8202-4bde-85e7-6eb9e093a933.png)

**Comment by AndyAPDevelopment** [comment]
Did you upload the folder from GitHub to your addons folder in WoW? It should be a separate addon under the name "Extra missions for Venture Plan".

**Comment by N6REJ** [comment]
Renaming it to "VenturePlanSoDMissions" worked.  Which makes sense now that I think about it since thats the .toc filename.

**Comment by hythloday** [comment]
What was the directory called before?

**Comment by N6REJ** [comment]
VenturePlanSoDMissions - main

**Comment by hythloday** [comment]
Ah, of course. I'll fix that in the next github version. Thanks for the bug report and glad you got it sorted.

**Comment by hythloday** [comment]
Looks like I already have! You might want to update to v0.07, some new spells in there.

**Comment by N6REJ** [comment]
can we get an indicator showings it's doing something?

**Comment by hythloday** [comment]
If you've installed it correctly, you'll get a pop-up asking you to modify VenturePlan. That's probably as good as it can do.

**Comment by N6REJ** [comment]
I did a full wipe and reinstall with no modifications other then the T you said too and did not get any notification or indication of any kind..
![image](https://user-images.githubusercontent.com/1850089/128361303-d5b2a109-fd0e-4489-8495-615afab4c874.png)
![image](https://user-images.githubusercontent.com/1850089/128361366-24f86803-3750-4feb-84b6-50847f8a8578.png)

**Comment by Eremeir** [comment]
> If you've installed it correctly, you'll get a pop-up asking you to modify VenturePlan. That's probably as good as it can do.

I've never seen this popup either and my missions are regularly failing even when predicted as success, same as the user above.
