### ISSUE TITLE
FEATURE: Add to wowuphub

### ISSUE THREAD

**Issue by N6REJ** [hythloday/VenturePlanSoDMissions#22]
Would be great to see this be a part of the wowup hub family
https://wowup.io/guide/section/wowup/hub

**Comment by hythloday** [comment]
Wowup already pulls from wowinterface, it seems like, and I don't want to monetize this addon. Is there an additional reason to host on Wowup Hub? It's also not very clear how to do so.

**Comment by N6REJ** [comment]
didn't seem to auto update on wowup.io and I assume you don't want it on curseforge so wowuphub is the alternative.

**Comment by hythloday** [comment]
Did you get the addon from wowinterface or github?

**Comment by N6REJ** [comment]
your addon from github.

**Comment by N6REJ** [comment]
here's their git page if its helpful https://github.com/WowUp/WowUp

**Comment by memskez** [comment]
Go to "Get Addons" and hit "Install from URL" - just paste github link there. Easy as that :)

**Comment by hythloday** [comment]
Going to close this, since there's a workaround and I don't see how to add to wowup's hub.
