### ISSUE TITLE
wrong value of spell 322

### ISSUE THREAD

**Issue by LostTemple1990** [hythloday/VenturePlanSoDMissions#25]
This spell may modify its maxHp according to its originalAtk instead of its originalHp
so the key **modMaxHP** may change to **modMaxHPATK**
modification as below
`{type="aura", target=4, duration=1, modMaxHP=80},`
to
`{type="aura", target=4, duration=1, modMaxHPATK=80},`
and here is a log for this
[sim.error.results.and.real.logs.txt](https://github.com/hythloday/VenturePlanSoDMissions/files/6923753/sim.error.results.and.real.logs.txt)

**Comment by LostTemple1990** [comment]
another bug for this spell
modify
`{type="nuke", target=0, damageATK=80, selfHealATK=80},`
to
`{type="nuke", target=0, damageATK=80, selfhealATK=80},`
difference between these two lines
**selfHealATK**  to  **selfhealATK**
the function qcast in vs.lua check the value of **selfhealATK** instead of **selfHealATK**
see function qcast() in vs.lua in line about 939(there is a line offset because I've modified many codes)
`if et == "nuke" and si.selfhealATK then`

**Comment by hythloday** [comment]
This is really great, thank you.
