### ISSUE TITLE
"Customary Shakedown" mission failed

### ISSUE THREAD

**Issue by aneri90** [hythloday/VenturePlanSoDMissions#26]
https://www.wowhead.com/mission=2303/customary-shakedown

**Comment by hythloday** [comment]
Unfortunately I can't do much with just the mission link. If you get this mission again, can you run this and post the output?

`/dump C_Garrison.GetMissionDeploymentInfo(CovenantMissionFrame:GetMissionPage().missionInfo.missionID)`
