### ISSUE TITLE
"Hunter Becomes the Hunted" mission failed

### ISSUE THREAD

**Issue by sgubbins** [hythloday/VenturePlanSoDMissions#28]
https://www.wowhead.com/mission=2312/hunter-becomes-the-hunted

https://www.wowhead.com/adventure-combatant-ability/heel-bite-346
"Heel Bite" 346
Deals $s1 Nature damage to the closest enemy and reduces their damage by $s2 for 2 rounds.

https://www.wowhead.com/adventure-combatant-ability/protective-wings-345
"Protective Wings" 345
Modifies the damage all allies take by $s1 for 3 rounds.

**Comment by hythloday** [comment]
Hey, thank you for these. I'm still waiting for this to come up so I can log it to see what the discrepancy is. I'm going to close it for now as there's no action I can take on it until it does.
