### ISSUE TITLE
"Adventure guide may be out of date" warning still showing

### ISSUE THREAD

**Issue by Psyshadow** [hythloday/VenturePlanSoDMissions#3]
Hi,

I'm unsure if this mission is actually in the addon? It doesn't have the warning next to the abilities that they aren't in the addon data, but when I auto-optimize it, the "!" warning still shows up saying "Adventure guide may be out of date" and I'm unsure of whether it's valid or not. 

Screenshot:

![ventureoutofdate](https://user-images.githubusercontent.com/87551941/126019343-6052ca19-974c-4150-9122-776b45ff9ac8.png)

**Comment by Zuescho** [comment]
This is because the Add-on Venture Plan has a Version Check in itself, this Add-on here only adds mission and does not edit the original code of the Add-on, so this is a Venture Plan Problem and can not be fixed.

**Comment by hythloday** [comment]
Yes, this is correct I'm afraid, there's not much that an external addon can do to change this for the moment.
