### ISSUE TITLE
Mission fail with new companion Elwyn

### ISSUE THREAD

**Issue by woefulwabbit** [hythloday/VenturePlanSoDMissions#34]
Logs attached:
[elwyn.log](https://github.com/hythloday/VenturePlanSoDMissions/files/7004579/elwyn.log)

Version is different, but the values for spell 306 match:
	[306]={type="aura", target=3, duration=3, modMaxHP=60, plusDamageDealtATK=40}, --Arcane Empowerment (UNVERIFIED)

**Comment by boomboo** [comment]
I don't know if it caused the failure but modMaxHP is wrong and should be modMaxHPATK

**Comment by BradCOnGitHub** [comment]
Found it. There's a hard coded 20 follower limit in Widgets.lua on line 1960. I'm not sure if you can fix that from another addon.

**Comment by FlipperPA** [comment]
@BradCOnGitHub I wish I'd read your comment first, I went hunting through the code myself... and just PR'd a change to the README!

**Comment by cremor** [comment]
@BradCOnGitHub and @FlipperPA Are you sure that fixing the 20 follower limit in Widgets.lua actually fixes this mission fail? Isn't that only a fix for the follow list display?

**Comment by BradCOnGitHub** [comment]
The other fix is needed too, but it doesn't cause a failure. It was just using a percentage based HP buff instead of a fixed amount, which was wrong.
