### ISSUE TITLE
Gatecrashers mission failure

### ISSUE THREAD

**Issue by BoethiusUK** [hythloday/VenturePlanSoDMissions#37]
It appears this mission (Gatecrashers) is causing a failure sometimes, and definitely mis-predicts.
Looking into this the mission has just 2 Stygian Bombadiers (back left and back right). They are listed as Ranged, but they actually use melee attacks. The prediction seems to be calculated with ranged auto attacks. So for instance it is showing a lot of damage to the troop in the front right position whereas this follower actually takes no damage (as the auto-attacks and cone attacks start at my front left and front middle troops).

I believe the Sygian Bombadier abilities to be:
autoCombatSpellID=11
autoCombatSpellID=347

Which both have the description about dealing damage to the closest enemy. Mousing over the Bombadiers to view the target dots shows the normal auto attack targets to be (incorrectly) the furthest troop but the cone ability target dots appear to correctly show the closest target being used for the start of the cone.

Full dump for mission:
[1]={
  locTextureKit="GarrMissionLocation-Maw",
  isExhausting=false,
  location="Korthia",
  xp=1000,
  enemies={
    [1]={
      autoCombatAutoAttack={
        description="Deal attack damage to the closest enemy.",
        autoCombatSpellID=11,
        duration=0,
        previewMask=0,
        name="Auto Attack",
        hasThornsEffect=false,
        schoolMask=1,
        icon=1064261,
        cooldown=0,
        spellTutorialFlag=1
      },
      isElite=false,
      scale=1.2000000476837,
      portraitFileDataID=4183235,
      autoCombatSpells={
        [1]={
          description="Deals 177 Shadow damage to all enemies in a cone emitting from the closest enemy.",
          autoCombatSpellID=347,
          duration=0,
          previewMask=0,
          name="Darkness from Above",
          hasThornsEffect=false,
          schoolMask=32,
          icon=457655,
          cooldown=2,
          spellTutorialFlag=0
        }
      },
      mechanics={
      },
      health=7080,
      role=3,
      name="Stygian Bombardier",
      boardIndex=9,
      height=0.5,
      displayID=101334,
      maxHealth=7080,
      attack=177
    },
    [2]={
      autoCombatAutoAttack={
        description="Deal attack damage to the closest enemy.",
        autoCombatSpellID=11,
        duration=0,
        previewMask=0,
        name="Auto Attack",
        hasThornsEffect=false,
        schoolMask=1,
        icon=1064261,
        cooldown=0,
        spellTutorialFlag=1
      },
      isElite=false,
      scale=1.2000000476837,
      portraitFileDataID=4183235,
      autoCombatSpells={
        [1]={
          description="Deals 177 Shadow damage to all enemies in a cone emitting from the closest enemy.",
          autoCombatSpellID=347,
          duration=0,
          previewMask=0,
          name="Darkness from Above",
          hasThornsEffect=false,
          schoolMask=32,
          icon=457655,
          cooldown=2,
          spellTutorialFlag=0
        }
      },
      mechanics={
      },
      health=7080,
      role=3,
      name="Stygian Bombardier",
      boardIndex=12,
      height=0.5,
      displayID=101334,
      maxHealth=7080,
      attack=177
    }
  }
}

**Comment by KyrosKrane** [comment]
Elaborating on what BoethiusUK said. Here's a screenshot from me mousing over the top-right enemy. Note that the Targets cone appears to be centered, not right-aligned as you'd expect.

![image](https://user-images.githubusercontent.com/458727/131044423-81e6449b-003a-460e-a7e7-68bc145d9665.png)

Compare that to the screenshot mousing over the left enemy:

![image](https://user-images.githubusercontent.com/458727/131044478-5e87685d-0bc8-4557-b33f-cd0210447552.png)

**Comment by BoethiusUK** [comment]
Just commenting on the screenshots you posted above the AE being cone being targeted on the central troop is actually correct, as this is classed as the closest target to the top right enemy position (your can see this if you run through the mission as the top right of your troops will take no damage in this mission (assuming none of your other troops die). It is the normal target shown at the top when you mouse over that is actually incorrect. This target should be the same target as the cone starts from (closest) but it actually shown/calculated as the furthest enemy. So in your top screen shot the target is shown as the top left troop whilst it should also be the central troop.

**Comment by zealvurte** [comment]
As you can see from the data posted, the Stygian Bombardier has a `role` of 3 (Ranged (Magic)), so VP sets the auto attack `spellID` to 15 (auto attack for furthest enemy), yet the data shows it should be 11 (auto attack for closest enemy).

You would need to create a new entry in `overrideAA` for each one, using their `boardIndex` and the `missionID`. Alternatively, rewrite the auto attack handling so it uses the data already provided for encounters rather than falling back to role based selection, thus eliminating the need for every `overrideAA` entry for encounters.

**Comment by hub-game** [comment]
Still failing...
I've already added 74038 and 74044 to overrideAA.

[Gatecrashers.txt](https://github.com/hythloday/VenturePlanSoDMissions/files/7147607/Gatecrashers.txt)

**Comment by zealvurte** [comment]
Assuming the tooltips for the enemies are now showing the right targets, I can see one additional issue specific to your log:

Cromas the Mystic has a role of `4` (Heal/Support), so VP sets the auto attack `spellID` to `15`, but it should be `11`. You need a new entry in `overrideAA` for `firstSpellID` `314` (key format is `1+4*firstSpellID`)
