### ISSUE TITLE
Newbie Tutorial?

### ISSUE THREAD

**Issue by Suzaru** [hythloday/VenturePlanSoDMissions#4]
Hey there!

This kinda is an issue, so I hope to find some explanation. As a - non tech afficionado - I can't get it to work. I changed the source of ventureplan, but what then? Downloading a zip (removing -main) and trying to load the addon doesn't work. I seem to miss something. Any chance for a newbie tutorial? <3 Thank you.

**Comment by simonstey** [comment]
I haven't tested it yet, but I'm pretty sure you have to copy those 2 files (.lua and .toc) into VenturePlan's original addon folder and then add the oneliner as outlined in the README.

**Comment by Neurotoxin001** [comment]
1. Create VenturePlanSoDMissions folder in \Interface\AddOns\
2. Put extra-vs-spells.lua and VenturePlanSoDMissions.toc from this github repo to VenturePlanSoDMissions folder
3. Open vs.lua in \Interface\AddOns\VenturePlan
4. Add `_G[_] = T` line right after `local SpellInfo = T.KnownSpells`

![image](https://user-images.githubusercontent.com/39812401/126027938-5501e937-547f-47de-a1f0-7ae65b1ad1dc.png)

**Comment by Suzaru** [comment]
> 1. Create **VenturePlanSoDMissions** folder in \Interface\AddOns\
> 2. Put **extra-vs-spells.lua** and **VenturePlanSoDMissions.toc** from this github repo to **VenturePlanSoDMissions** folder
> 3. Open **vs.lua** in \Interface\AddOns\VenturePlan
> 4. Add `_G[_] = T` line right after `local SpellInfo = T.KnownSpells`
> 
> ![image](https://user-images.githubusercontent.com/39812401/126027938-5501e937-547f-47de-a1f0-7ae65b1ad1dc.png)

Thank you for your help. I really appreciate it. That's actually what I did, but WoW doesn't show a "VenturePlanSoDMissions" Addon ingame. Is that how it's supposed to be? I was expecting to see an additional addon loaded. Thank you for your help!

**Comment by Neurotoxin001** [comment]
@Suzaru 
![image](https://user-images.githubusercontent.com/39812401/126036843-b22b69b5-f568-467f-b3d7-44d3c1bebd81.png)

**Comment by hythloday** [comment]
@Suzaru you might have a "VenturePlanSoDMissions-main" folder in your addons directory that you need to rename, I'll fix the issue that's causing that. Check back for a 0.04 release that should be easier to install.

**Comment by hythloday** [comment]
> 
> 
> I haven't tested it yet, but I'm pretty sure you have to copy those 2 files (.lua and .toc) into VenturePlan's original addon folder and then add the oneliner as outlined in the README.

Nope, this is just a normal addon that you install into your Interface/Addons directory.

**Comment by hythloday** [comment]
@Suzaru I'm going to close this because I think once this is available on an addon site - which it should be soon - you won't run into this issue. But if you do, please reopen it and I'll try to add more documentation to cover what went wrong.
