### ISSUE TITLE
"Companions" section of mission window is reverting back to default list, instead of showing addon's custom layout with icons

### ISSUE THREAD

**Issue by ZaneBusby** [hythloday/VenturePlanSoDMissions#41]
After obtaining Renown 62 and gaining access to the new companion, when going to the mission table and opening a mission to assign companions, the companion tab on the side is showing the default UI list format, instead of showing VenturePlan's custom UI with the rows of icons. I have tried re-installing both VenturePlan and VenturePlanSoDMissions and then re-opening the game client, but that did not fix the issue.

![image](https://user-images.githubusercontent.com/63590070/131192231-3040ec0d-0789-4120-b651-a267044be992.png)

**Comment by epiktetov** [comment]
Duplicate, see issue [#33 ](https://github.com/hythloday/VenturePlanSoDMissions/issues/33) for explanation and the fix

**Comment by ZaneBusby** [comment]
My bad, misread the title of that ticket so didn't realise it was the same issue. Thanks
