### ISSUE TITLE
How to export dump

### ISSUE THREAD

**Issue by N6REJ** [hythloday/VenturePlanSoDMissions#42]
I ran the dump as the mission was incorrectly predicted and it did output info in the chat box but I see no way to copy/paste that info.

**Comment by BoethiusUK** [comment]
I think you need to use an addon to be able to copy / paste it. When I posted a log I used the ChatCopyPaste addon (https://www.curseforge.com/wow/addons/chat-copy-paste) which puts a little icon on the chat window allowing you to copy the text. Only really used it for doing that one log though so can't vouch for it other than it seemed to work ok for me. (note that the chat log seems to be quite limited to how much it shows so for a long log a lot would probably get cut off this way. I don't know if there is a better solution though).

**Comment by zealvurte** [comment]
I've suggested a different approach so you can get the actual logs in future. See issue #43.
