### ISSUE TITLE
Multiple Mission Failures: A Few Too Many

### ISSUE THREAD

**Issue by BoethiusUK** [hythloday/VenturePlanSoDMissions#44]
I have had repeat failures of this mission when success has been predicted. The failure appears to be due to the same root cause as [#37](https://github.com/hythloday/VenturePlanSoDMissions/issues/37) just with different troops.
This has a full enemy board of Unruly Patrons. VP is predicting with their auto-attacks as ranged attacks, so shows the top middle troop taking no damage and receiving no incoming attacks. What actually happens is that the auto-attacks target the closest so the front row takes a lot more damage than is predicted.
Again, like the other task the Unruly Patron has a role of 3 but should use SpellID 11 (attack closest) for auto-attacks but instead the simulation is using SpellID 11 (attack furthest)

Here is the log for one of the Unruly Patrons showing it should be using SpellID=11 for it's auto-attacks.

[6]={
      autoCombatAutoAttack={
        description="Deal attack damage to the closest enemy.",
        autoCombatSpellID=11,
        duration=0,
        previewMask=0,
        name="Auto Attack",
        hasThornsEffect=false,
        schoolMask=1,
        icon=1064261,
        cooldown=0,
        spellTutorialFlag=1
      },
      isElite=false,
      scale=1.2000000476837,
      portraitFileDataID=4183244,
      autoCombatSpells={
        [1]={
          description="Thunk!  Deals 103 Shadow damage to the furthest enemy.",
          autoCombatSpellID=332,
          duration=0,
          previewMask=0,
          name="Emptied Mug",
          hasThornsEffect=false,
          schoolMask=32,
          icon=463489,
          cooldown=2,
          spellTutorialFlag=1
        }
      },
      mechanics={
      },
      health=4140,
      role=3,
      name="Unruly Patron",
      boardIndex=5,
      height=0.5,
      displayID=101543,
      maxHealth=4140,
      attack=69
    },

There was a potential fix mentioned in the other task linked above that involved modifying overideAA with the board index and missionID which I assume would also work for this mission. I'm not really sure what all the values there mean but if anyone has done this for the other mission (or does it for this one) and has the modification they could share that would be useful.

**Comment by xinye83** [comment]
[a_few_too_many_log.txt](https://github.com/hythloday/VenturePlanSoDMissions/files/7110874/a_few_too_many_log.txt)

**Comment by zealvurte** [comment]
They would need entries in `overrideAA` for `missionID` `2304` with `slot` `5` to `12`.

**Comment by hub-game** [comment]
> They would need entries in `overrideAA` for `missionID` `2304` with `slot` `5` to `12`.
How to do this? What exactly should be added to `overrideAA`?

**Comment by BoethiusUK** [comment]
Thanks. To save anyone else who wants to do this having to do the calculations. The values that would need adding to overrideAA for this mission would be:

`[73742]=0, [73744]=0, [73746]=0, [73748]=0, [73750]=0, [73752]=0, [73754]=0, [73756]=0`

**Comment by Divergentcurl** [comment]
For people wondering where the above numbers come from, they are the result of using the fomula in https://github.com/hythloday/VenturePlanSoDMissions/issues/45#issuecomment-913241992 (i.e. `4+2*slot+32*missionID`). Applying this fix seems to have fixed this issue for me
