### ISSUE TITLE
Mission Failed: Catastrophic Skeleton Infestation

### ISSUE THREAD

**Issue by glassleo** [hythloday/VenturePlanSoDMissions#46]
[Catastrophic Skeleton Infestation](https://www.wowhead.com/mission=2168/catastrophic-skeleton-infestation)

This very same mission has failed for me a bunch of times now as a Necrolord with low level followers.

Log output (via #43):

- [VenturePlanSoDMissions_Logs.lua.txt](https://github.com/hythloday/VenturePlanSoDMissions/files/7107877/VenturePlanSoDMissions_Logs.lua.txt)

**Comment by zealvurte** [comment]
As noted in https://github.com/hythloday/VenturePlanSoDMissions/issues/17#issuecomment-894707406, `spellID` `107` needs updating to be `target=0` for both effects, `damageATK=150` for the first effect, and `plusDamageTakenATK=50` for the second.

**Comment by BoethiusUK** [comment]
Just a quick correction here. I have run Plague Deviser Marilth through various missions and logged them (He is the one that casts spellID 107 - Volatile Solvent.
This actually hits for 1.5* normal damage so the first effect should actually be damageATK=150 not damageATK=50 I believe. The below appears to be the correct values for that spell.
```
	[107]={
		{type="aura", target=0, damageATK=150, duration=4, nore=true},
		{type="aura", target=0, plusDamageTakenATK=50, duration=3},
	},
```
The following snippet from one log shows all the info for this. Normal auto-attack for 420 at [3], application of debuff part at [4] then the spellID 107 hitting for 630 at [5] which is 150% attack. (Note this means his abilities actually match his tool tip now). I have multiple other logs showing the same thing.

```
					}, -- [3]
					{
						["casterBoardIndex"] = 0,
						["type"] = 1,
						["schoolMask"] = 1,
						["targetInfo"] = {
							{
								["oldHealth"] = 5360,
								["boardIndex"] = 11,
								["points"] = 420,
								["maxHealth"] = 5360,
								["newHealth"] = 4940,
							}, -- [1]
						},
						["auraType"] = 0,
						["effectIndex"] = 0,
						["spellID"] = 15,
					}, -- [4]
					{
						["casterBoardIndex"] = 0,
						["type"] = 7,
						["schoolMask"] = 32,
						["targetInfo"] = {
							{
								["oldHealth"] = 5106,
								["boardIndex"] = 6,
								["maxHealth"] = 5360,
								["newHealth"] = 5106,
							}, -- [1]
						},
						["auraType"] = 8,
						["effectIndex"] = 0,
						["spellID"] = 107,
					}, -- [5]
					{
						["casterBoardIndex"] = 0,
						["type"] = 5,
						["schoolMask"] = 32,
						["targetInfo"] = {
							{
								["oldHealth"] = 5106,
								["boardIndex"] = 6,
								["points"] = 630,
								["maxHealth"] = 5360,
								["newHealth"] = 4476,
							}, -- [1]
						},
						["auraType"] = 0,
						["effectIndex"] = 0,
						["spellID"] = 107,
					}

```

**Comment by zealvurte** [comment]
You're right, I managed to misread and the wrong value in my data twice. 🤦‍♂️ It is `150` for the first effect (edited comments to fix).
