### ISSUE TITLE
(Need more logs)Wrong value of spell 333

### ISSUE THREAD

**Issue by LostTemple1990** [hythloday/VenturePlanSoDMissions#47]
I found it yesterday but I don't have enough log to check out this value
Here is a log for this
[sim error results and real logs.txt](https://github.com/hythloday/VenturePlanSoDMissions/files/7114966/sim.error.results.and.real.logs.txt)
pay attention to the enemy in slot 5 in **turn 2**(last action in turn 2)
the enemy in slot 5 owns a -210 atk reduce aura and a 40% atk aura(according to spell 333)
its original attack was 350 and it dealt 195 damage  
`（350-210） * 1.4 = 196`  in sim
(1 value offset due to precision while caculating,it's hard to explain so just ignore it in this case)
but in real log,it dealt 280 damage
I supposed that the value is caculated by
`（350-210） * 2.0 = 280`
the spell 333 may change the key **modDamageDealt** from value **40** to **100**

see also the last action in turn 3
the enemy gains two -20% atk auras ,-210 atk aura and 40% atk aura(according to spell 333)
but it dealt 168 damage in real log
this value might caculate by 
`（350-210） * 2.0 * (1-0.2-0.2)= 168`

It needs more logs to prove this fix because no one points out this bug since the config of this spell was used over nearly 2 months

**Comment by zealvurte** [comment]
See https://github.com/LostTemple1990/Issues-of-self-debugged-VenturePlan/issues/7 for correction.
