### ISSUE TITLE
Mission failed: Unexpected Delays

### ISSUE THREAD

**Issue by hub-game** [hythloday/VenturePlanSoDMissions#48]
Enemies used abilities #333 #334 #335. Don't know which one is broken.
Hope this helps.
[VenturePlanSoDMissions.txt](https://github.com/hythloday/VenturePlanSoDMissions/files/7127268/VenturePlanSoDMissions.txt)

**Comment by zealvurte** [comment]
It's 333. It should be `plusDamageDealtATK`, not `modDamageDealt`.

**Comment by hub-game** [comment]
[Unexpected Delays.txt](https://github.com/hythloday/VenturePlanSoDMissions/files/7175788/Unexpected.Delays.txt)
Still fails on that mission.

**Comment by zealvurte** [comment]
I forgot to check the encounters too...

P.O.S.T Worker has a role of `4` (Heal/Support), so VP sets the auto attack `spellID` to `15`, but it should be `11`. You need a new entry in `overrideAA` for `missionID` `2305` and `slot` `6` to `8` (key format is `4+2*slot+32*missionID`).

Defective Sorter has a role of `3` (Ranged (Magic)), so VP sets the auto attack `spellID` to `15`, but it should be `11`. You need a new entry in `overrideAA` for `missionID` `2305` and `slot` `10` to `12` (key format is `4+2*slot+32*missionID`).
