### ISSUE TITLE
Mission failed: Learn from the Master

### ISSUE THREAD

**Issue by hub-game** [hythloday/VenturePlanSoDMissions#51]
[Learn from the Master.txt](https://github.com/hythloday/VenturePlanSoDMissions/files/7131206/Learn.from.the.Master.txt)

**Comment by zealvurte** [comment]
The Security Specialist is auto-attack `spellID` `15` instead of `11` in the sim, due to its `role` being `2` (Ranged (Physical)). It would need an entry in `overrideAA` for `missionID` `2301` with `slot` `9`.

**Comment by Psyshadow** [comment]
Hi! So, Ive been reading each of these and I don't understand how to make an entry like that into venture plan's code. I was able to use one of the comments to find the line of code that "override AA" is on in and I saw your comment with the "key format" but I don't understand what that means nor do I understand where after the term override AA to actually enter each of these fixes. Would you mind explaining to someone with less (but some) coding experience than ideal? I would GREATLY appreciate it. Thank you!!
-psy

**Comment by zealvurte** [comment]
If you're struggling with the concept of adding a key-value pair to a table in Lua, it sounds like your coding experience was next to `nil`, and you really shouldn't be editing code until you learn the necessary basics. This isn't really the place to ask for such help, and there's plenty of resources out there if you want to learn yourself.

**Comment by TruthNZ** [comment]
I'm an experienced lua coder, who uses it professionally (although for Kong, not WoW). And I needed assistance to work out what needed to be done for those.
Mask based data structures are very old school, and not the easiest to understand.

Each key in the overrideAA is a mask of `4+2*slot+32*missionId` (or `1+4*spell` - but we're not using that here).
As far as I can tell the value doesn't actually matter, it's just checking to see if there is an entry in this table. Hence the values are just set to 0.

**Comment by zealvurte** [comment]
Your situation is not comparable, as the table name and key format were already known.

The values do matter btw (they're compared to `0`), but due to the nature of the data and how it's being used, they are always going to be `0` unless Blizzard make a mistake (which has only happened with this once, so far).

**Comment by Gaviin1242** [comment]
So I'm curious... is anyone actually actioning these issues?  Like, will the extra-vs-spells.lua file be updated to fix these things?

I'm not demanding anything, just wondering if I'll need to look through each ticket and figure out how to make updates myself.  These mission failures are starting to annoy me.  :)

**Comment by TruthNZ** [comment]
A lot of these are modifications to the original Venture Plan - which the original Author won't let us change. And the changes are to a variable scoped inside a block we can't update from another addon.

So unfortunately you'll have to update them yourself.

It would be nice to put the changes somewhere people can copy/paste - like we have for the Renown 62 hotfix.

**Comment by Gaviin1242** [comment]
That would be really great because after looking at vs.lua and this whole overrideAA thing... yeah, it's a bit out of my league.  :(

**Comment by Divergentcurl** [comment]
I have gathered the fixes I have applied so far and a guide on how to apply them in #60. I hope it helps you.
