### ISSUE TITLE
Mission failed: On Wings of Ferocity

### ISSUE THREAD

**Issue by hub-game** [hythloday/VenturePlanSoDMissions#52]
[On Wings of Ferocity.txt](https://github.com/hythloday/VenturePlanSoDMissions/files/7134949/On.Wings.of.Ferocity.txt)

**Comment by zealvurte** [comment]
The Razorwing Gnasher is auto-attack `spellID` `15` instead of `11` in the sim, due to its `role` being `2` (Ranged (Physical)). It would need an entry in `overrideAA` for `missionID` `2311` with `slot` `6`.

**Comment by vitor-f2f** [comment]
I think it isn't taking the spell (Razorwing Buffet) into account in the prediction, cuz it tells me my follower on upper middle is gonna finish at full health after 18 rounds while I don't have anything that would heal it up, and Razorwing Buffet hits all targets. It seems implemented correctly in extra-vs-spells.lua.
https://i.imgur.com/abB2rpl.png
