### ISSUE TITLE
Mission failed: Sharp Hides, Sharper Teeth

### ISSUE THREAD

**Issue by hub-game** [hythloday/VenturePlanSoDMissions#54]
[Sharp Hides Sharper Teeth.txt](https://github.com/hythloday/VenturePlanSoDMissions/files/7156411/Sharp.Hides.Sharper.Teeth.txt)

**Comment by zealvurte** [comment]
Elwyn has a `role` of `4` (Heal/Support), so VP sets the auto-attack `spellID` to `15`, but it should be `11`. You need a new entry in `overrideAA` for `firstSpellID` `306` (key format is `1+4*firstSpellID`)
