### ISSUE TITLE
Lua Error on opening Mission

### ISSUE THREAD

**Issue by valxantr** [hythloday/VenturePlanSoDMissions#55]
I finally collected all followers that are avalable up until now and then when opening up a new mission, i get spammed with lua errors. BugSack collects them as the following:

[ventureplanfollowererror.txt](https://github.com/hythloday/VenturePlanSoDMissions/files/7160755/ventureplanfollowererror.txt)

**Comment by TruthNZ** [comment]
Refer https://github.com/hythloday/VenturePlanSoDMissions/issues/33

**Comment by valxantr** [comment]
> 
> 
> Refer #33

Thank you very much! I must have been blind while i was searching for a solution. This works just fine.
