### ISSUE TITLE
On load warning [Minor annoyance]

### ISSUE THREAD

**Issue by ghost** [hythloday/VenturePlanSoDMissions#58]
I understand the purpose, and that I may be being a bit petty, but could we get a disable option for this? I have to routinely reload my UI throughout the day, mainly from guild frame related issues, and getting this every time is kinda annoying.

**Comment by TruthNZ** [comment]
Umm, I'm not getting any warnings on load/reload.

Could you add the message to your issue? (and/or screenshot)

**Comment by ghost** [comment]
![Screenshot 001449](https://user-images.githubusercontent.com/17183816/134275467-3c2c9d61-ea57-48d0-aecd-885462c739e9.png)
Here you go.

**Comment by TruthNZ** [comment]
That means you haven't modified VenturePlan as per the Getting it Running instructions at https://github.com/hythloday/VenturePlanSoDMissions

**Comment by ghost** [comment]
Ah ok, I just installed it from wowinterface and there was no such mention of instructions there. I don't support meddling with other peoples addons in this way, so I'll be removing this from my game. Have a good day.

**Comment by TruthNZ** [comment]
Yup, sorry. The original author has abandoned VenturePlan, but won't let anyone updated it.
So instructions for modifying it - so this addon can update it is as good as we can do.
