### ISSUE TITLE
New follower bug

### ISSUE THREAD

**Issue by Talimar** [hythloday/VenturePlanSoDMissions#59]
Not sure if you can fix this but this week's new follower seems to have broken Ventureplan a bit:

20x VenturePlan\Widgets.lua:546: attempt to index local 'self' (a nil value)
[string "@VenturePlan\Widgets.lua"]:546: in function <VenturePlan\Widgets.lua:539>
[string "@VenturePlan\Widgets.lua"]:722: in function `Refresh'
[string "@VenturePlan\MissionView.lua"]:677: in function <VenturePlan\MissionView.lua:671>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@VenturePlan\Util.lua"]:205: in function `ShowMission'
[string "@VenturePlan\Widgets.lua"]:242: in function <VenturePlan\Widgets.lua:241>

Locals:
self = nil
info = <table> {
 isAutoTroop = false
 followerTypeID = 123
 soFavorite = 0
 iLevel = 800
 isCollected = true
 classAtlas = "raceicon-undead-male"
 autoCombatSpells = <table> {
 }
 isTroop = false
 garrFollowerID = 1261
 missionTimeEnd = 24165.877000
 displayHeight = 0.500000
 levelXP = 7100
 status = "On Mission"
 level = 39
 scale = 0.700000
 classSpec = 345
 portraitIconID = 3684879
 displayIDs = <table> {
 }
 isFavorite = false
 role = 3
 displayScale = 1
 autoCombatantStats = <table> {
 }
 xp = 3250
 quality = 5
 health = 1209
 isMaxLevel = false
 name = "Plague Deviser Marileth"
 followerID = "0x000000006A37E29C"
 height = 1.200000
 isSoulbind = true
 maxHealth = 1440
 className = "Plague Deviser"
}
s = nil
onMission = true
inTG = nil
vc = 0.250000
dc = 0.650000
mc = <table> {
 GetRGB = <function> defined @SharedXML\Color.lua:20
 OnLoad = <function> defined @SharedXML\Color.lua:9
 b = 0.498000
 GenerateHexColorMarkup = <function> defined @SharedXML\Color.lua:51
 WrapTextInColorCode = <function> defined @SharedXML\Color.lua:55
 GenerateHexColor = <function> defined @SharedXML\Color.lua:47
 GetRGBA = <function> defined @SharedXML\Color.lua:28
 IsEqualTo = <function> defined @SharedXML\Color.lua:13
 g = 0.498000
 r = 0.498000
 SetRGBA = <function> defined @SharedXML\Color.lua:36
 GetRGBAsBytes = <function> defined @SharedXML\Color.lua:24
 SetRGB = <function> defined @SharedXML\Color.lua:43
 GetRGBAAsBytes = <function> defined @SharedXML\Color.lua:32
}
mtl = "5h"
(*temporary) = 17620
(*temporary) = 2
(*temporary) = true
(*temporary) = true
(*temporary) = <function> defined =[C]:-1
(*temporary) = "5h"
(*temporary) = "%dh"
(*temporary) = 5
(*temporary) = "5h"
(*temporary) = 5
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'self' (a nil value)"
S = <table> {
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <table> {
 }
  = <table> {
 }
  = <unnamed> {
 }
  = <table> {

**Comment by Quiksmage** [comment]
as soon as i received the new companion the layout changed a bit too 
![image](https://user-images.githubusercontent.com/12449533/134416069-d68d2d42-ac14-4a33-b230-848e67edd322.png)

**Comment by TruthNZ** [comment]
There's a fix listed in issue https://github.com/hythloday/VenturePlanSoDMissions/issues/33
