### ISSUE TITLE
Mission failled: Hunter Becomes the Hunted

### ISSUE THREAD

**Issue by hub-game** [hythloday/VenturePlanSoDMissions#62]
[Hunter Becomes the Hunted.txt](https://github.com/hythloday/VenturePlanSoDMissions/files/7260777/Hunter.Becomes.the.Hunted.txt)

**Comment by zealvurte** [comment]
Frenzied Razorwing has a role of `5` (Ranged (Physical)), so VP sets the auto-attack `spellID` to `15`, but it should be `11`. You need a new entry in `overrideAA` for `missionID` `2312` and `slot` `5` (key format is `4+2*slot+32*missionID`).
