### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by V1P3R** [hythloday/VenturePlanSoDMissions#63]
for i=1,#C_Garrison.GetFollowers(123) do
on the follower count error is more efficient than
for i=1,99 do

though it can only show 24 and might lead to an error when you gain new followers, so perhaps hardcoding to 24 instead of 99 is the way to go.

**Comment by TruthNZ** [comment]
It leads to errors if you get a new follower and don't reload before opening your mission table.

Frankly I think that's a small price to pay. It's easy to reload. And is better than having to do more updates regularly.

**Comment by Divergentcurl** [comment]
I was wondering if this is still being maintained as well. If not, I wouldn't mind taking up that responsibility.

**Comment by woefulwabbit** [comment]
> I was wondering if this is still being maintained as well. If not, I wouldn't mind taking up that responsibility.

This might be necessary, seeing as @hythloday hasn't been active in github since Aug 20. Unless someone else active has write access. @FlipperPA perhaps?

**Comment by majtymit** [comment]
bump

**Comment by k1ck3r** [comment]
please, as i wrote in another issue, take care of this repo (clone it, but keep it updated) until the owner decided to answer. just make a PR, before letting us know link to your PR

**Comment by Divergentcurl** [comment]
I have forked this repo and am maintaining a [cumulative-fixes](https://github.com/Divergentcurl/VenturePlanSoDMissions/tree/cumulative-fixes) branch, gathering all known fixes. It should be a bit more user-friendly than following the instructions in #60. Also, this branch now has fixes for 9.1.5.

**Comment by FlipperPA** [comment]
Sorry I can't take over, @woefulwabbit - I'm in the process of moving houses. I'll contribute to @Divergentcurl's fork.

**Comment by FlipperPA** [comment]
I've added a few PR fixes to @Divergentcurl's fork to the `cumulative-fixes` branch.

**Comment by k1ck3r** [comment]
@Divergentcurl Have one small suggestion, it's more QoL than actual funtion... Would you be so kind and rename the addon from `Extra Missions for Venture Plan` to something more like `Venture Plan (Extra Missions)`

Renaming it, will put your (and all other people's here work) addon to the alphabetical _proper_ place - now it's the very start of list, while actual Venture Plan is at the end.

**Comment by Divergentcurl** [comment]
I agree and now remember that I was confused at first by the name in WoW as well. With the latest commit I have made it consistent with the other naming of the addon (the folder and on WoWInterface)

**Comment by k1ck3r** [comment]
Thank you SO MUCH !!! <3  now publish this shit into WoWup :"))))
