### ISSUE TITLE
9.2 changes

### ISSUE THREAD

**Issue by zealvurte** [hythloday/VenturePlanSoDMissions#69]
9.2 only needs some new spells.

- 25 new enemy spells across multiple new missions:
```lua
	[350]={type="nuke", damageATK=25, target="cleave"},
	[351]={type="nuke", damageATK=75, target=1, firstTurn=4},
	[352]={type="nop"},
	[353]={type="nop"},
	[354]={type="nuke", damageATK=400, target="enemy-front", firstTurn=5},
	[355]={type="passive", modDamageDealt=-25, target=1},
	[357]={type="passive", modDamageDealt=-50, target=0},
	[358]={type="nuke", damageATK=400, target="enemy-front", firstTurn=5},
	[359]={type="aura", damageATK=50, target=1, duration=0, noFirstTick=true, echo=3},
	[360]={type="nuke", damageATK=50, target="enemy-front"},
	[361]={type="nuke", damageATK=75, target="enemy-front"},
	[362]={type="nuke", damageATK=120, target=1},
	[363]={type="aura", modDamageDealt=10, target="friend-front-soft", duration=2},
	[364]={type="taunt", target="all-enemies", duration=2},
	[365]={type="aura", modDamageTaken=50, target=0, duration=1},
	[366]={type="nuke", damageATK=50, target="enemy-front"},
	[367]={type="nuke", damageATK=75, target="cone"},
	[368]={type="nuke", damageATK=60, target=1},
	[369]={
		[1]={type="nop"},
		[2]={type="aura", damageATK=50, target="all-enemies", duration=0, noFirstTick=true, echo=2},
	},
	[370]={type="aura", modDamageDealt=-50, target="all-enemies", duration=2},
	[371]={type="aura", modDamageTaken=-25, target="all-other-allies", duration=2},
	[372]={type="nuke", damageATK=40, target="enemy-front"},
	[373]={
		[1]={type="nuke", damageATK=100, target=1},
		[2]={type="heal", healATK=100, target=4},
	},
	[374]={
		[1]={type="nuke", damageATK=100, target=1},
		[2]={type="heal", healATK=40, target=4},
	},
	[375]={type="aura", modDamageDealt=-20, target="all-enemies", duration=2},
```
Be aware that:
- Spell `369` Power of Domination (in mission `2340` Giant Footprints in the Sand) ~~is bugged and unintentionally ticks for 100% of a target's health rather than flat damage, so you'll want a good percentage damage reduction to get through it - they seem to have no interest in fixing this~~
  - Hotfix: Now correctly ticks for flat damage, and has no initial tick
- New missions had no tuning passes on PTR and as a result mission `2331` Into the Wilds, and `2334` Construction Error ~~don't appear to be winnable (for Night Fae at least) - again, they don't seem interested in fixing this~~
  - Hotfix: Health and attack reduced on enemies, and damage of 1 spell effect reduced for these 2 missions and some other 9.2 ones

**Comment by gaveer** [comment]
@zealvurte  in which file i add these changes ?
in extra-vs-spells file there is 2 section : 
T.MoreSpells   and T.UnverifiedSpells

**Comment by zealvurte** [comment]
`T.MoreSpells` afaik.

**Comment by hythloday** [comment]
Thanks for this, I'm not playing at the moment but I'll get this merged when I have a moment.

@zealvurte could you message me on Discord? ItsJames#0297

**Comment by solkarnar** [comment]
Just dropping in to say thanks to everyone working on this!

**Comment by Johnydoe1977** [comment]
Hi, has the new 9.2 missions been included?

**Comment by woefulwabbit** [comment]
@hythloday You'll want to merge from https://github.com/Divergentcurl/VenturePlanSoDMissions/tree/cumulative-fixes too

**Comment by tgeisterfer** [comment]
i havent updated ventureplan in ages. where do i start with all the new updates

**Comment by glassleo** [comment]
> i havent updated ventureplan in ages. where do i start with all the new updates

Yeah this is very all over the place and disorganized.

**Comment by greghudson** [comment]
> [352]={type="aura", modDamageTaken=30, target=4},
> [353]={type="aura", modDamageDealt=20, target=1},

I think these need a `duration=`; otherwise I get lua errors predicting Automa Attack.  I'm guessing the value should be 2 based on in-game tooltips, but I'm less certain about that.

**Comment by zealvurte** [comment]
Ah, I forgot I had to modify VP for those 2 special cases. Simulations showed these auras with no duration are never cast, so I've replaced them with nop for VP.

**Comment by Divergentcurl** [comment]
> > i havent updated ventureplan in ages. where do i start with all the new updates
> 
> Yeah this is very all over the place and disorganized.

I was frustrated by this as well. That is why I have gathered all the fixes I know in my [cumulative fixes](https://github.com/Divergentcurl/VenturePlanSoDMissions/tree/cumulative-fixes) branch. If anyone notices anything missing, please let me know and I will add it.

**Comment by Briandris** [comment]
I'm confused and fairly new to Github. I really appreciate those of you who are keeping this addon functional for people like me who might as well be reading a foreign language. 

Previously, I followed instructions for "Getting it Running" and "Hotfixing the Code" for extra companions. I installed hythloday's Ventureplansodmissions. It was working great until 9.2 hit this week.

I don't know how to use/install the cumulative fixes branch. There's nothing to download or copy like the "latest release" button for Hythloday's page.

I did see the added change for overideAA and put that in the ventureplan file.
I deleted the old VentureplanSoDMissions and did a fresh download and put it in the addons file
I copy/pasted the new spells kindly posted from @zealvurte. 

When I load WoW and the open the adventure table, there are alerts on the missions Prison Break, Gatecrashers, Customary 
Shakedown, Defeat the World Eaters and Piratical Problems. Could someone help me understand where I likely went wrong please?

**Comment by glassleo** [comment]
> I don't know how to use/install the cumulative fixes branch. There's nothing to download or copy like the "latest release" button for Hythloday's page.

[Go to Divergentcurl's repo page for the branch](https://github.com/Divergentcurl/VenturePlanSoDMissions/tree/cumulative-fixes) and click the green "Code" button in the top right corner and select "Download ZIP". 

Note that the folder needs to be renamed to ``VenturePlanSoDMissions`` for the game to load it properly. (It will be named ``VenturePlanSoDMissions-cumulative-fixes`` in the ZIP archive).

**Comment by Briandris** [comment]
@glassleo Fixed! Thanks so much!

**Comment by siweia** [comment]
For mission 2323, https://www.wowhead.com/mission=2323/joint-operations-the-hunt, there should be four rewards include follower XP. VP only displayed three reward icons and anchoring weried.
![112](https://user-images.githubusercontent.com/1502922/155446202-a3d04fab-2d72-42b7-b790-18bfd22a69c7.png)

**Comment by solkarnar** [comment]
> For mission 2323, https://www.wowhead.com/mission=2323/joint-operations-the-hunt, there should be four rewards include follower XP. VP only displayed three reward icons and anchoring weried. ![112](https://user-images.githubusercontent.com/1502922/155446202-a3d04fab-2d72-42b7-b790-18bfd22a69c7.png)

Seeing that this mission requires 5 icons (1 exp + 4 rep), could it be due to an icon overflow problem? @zealvurte

**Comment by zealvurte** [comment]
Almost certainly. I noticed it, but didn't look into resolving it at the time or since, as it's a one off so far.

**Comment by zealvurte** [comment]
There's been a hotfix to fix (most of) the issues I highlighted in the data. I've updated the original post with the changes.

**Comment by Divergentcurl** [comment]
@zealvurte Thanks for the swift update. I have updated my branch as well.

**Comment by LostTemple1990** [comment]
[sim error results and real logs.txt](https://github.com/hythloday/VenturePlanSoDMissions/files/8172349/sim.error.results.and.real.logs.txt)
enemy in slot 5 cast spell 363 to itself in turn 13
the value of key "target" to spell 363 may be `friend-front-soft` but not `friend-front-hard`

**Comment by zealvurte** [comment]
Verified and corrected, thanks - my logs clearly didn't encounter a case where it made a difference.

Also taking another look at my logs for spell 46, I have none that verify a difference between hard and soft either, so I've unverified that.

**Comment by Barleduq** [comment]
> > I don't know how to use/install the cumulative fixes branch. There's nothing to download or copy like the "latest release" button for Hythloday's page.
> 
> [Go to Divergentcurl's repo page for the branch](https://github.com/Divergentcurl/VenturePlanSoDMissions/tree/cumulative-fixes) and click the green "Code" button in the top right corner and select "Download ZIP".
> 
> Note that the folder needs to be renamed to `VenturePlanSoDMissions` for the game to load it properly. (It will be named `VenturePlanSoDMissions-cumulative-fixes` in the ZIP archive).

Ok, so the zip file from the cumulative-fixes branch should *replace* the current version of VPSODM 0.10 ?  Or is this more files that I have to insert in places?  (I'm comfortable modifying files, but I don't always understand what's going on with repos and commits - my coding days were all in college, way before version control was a thing.)

**Comment by glassleo** [comment]
> Ok, so the zip file from the cumulative-fixes branch should _replace_ the current version of VPSODM 0.10 ? Or is this more files that I have to insert in places? (I'm comfortable modifying files, but I don't always understand what's going on with repos and commits - my coding days were all in college, way before version control was a thing.)

I'm assuming you managed to download the ZIP file correctly, and also followed the instructions for modifying the VenturePlan addon already.

1. Open your WoW AddOns folder (usually ``C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns`` if you are running Windows)
2. Delete the folder named ``VenturePlanSoDMissions`` inside the AddOns folder if it exists
3. Open up the ZIP file you downloaded from Diventcurl's GitHub
4. Inside the ZIP, there will be a folder named ``VenturePlanSoDMissions-cumulative-fixes``, drag this into your AddOns folder to extract it, then close the ZIP file
5. Rename the folder ``VenturePlanSoDMissions-cumulative-fixes`` inside your AddOns folder to ``VenturePlanSoDMissions``
6. That's it

**Comment by Barleduq** [comment]
Yes, I've modified the Widgets file when that fix came out in August, and the vs.lua file just now.  I downloaded VPSoDM from wowinterface.com.  That folder only has 2 files in it, and the cum fixes folder has 2 folders and 3 files more. So I was making sure I was doing the correct thing with it. 
I hope I can hear about those fixes being included in the main file (and, presumably uploaded to WoWI) so I can continue my usual addon installation habits. 

Thank you for the fast reply!
-Barleduq

**Comment by Jevnaker** [comment]
I tried to use this and now this addon (the ventureplan modifier one) thinks i havent modified the ventureplan files required.

**Comment by Divergentcurl** [comment]
Please have a look at [https://github.com/Divergentcurl/VenturePlanSoDMissions/tree/cumulative-fixes#getting-it-running](https://github.com/Divergentcurl/VenturePlanSoDMissions/tree/cumulative-fixes#getting-it-running). It should help you get these fixes running. You only have to do this once.

**Comment by Jevnaker** [comment]
ok ty

**Comment by Jevnaker** [comment]
the issue i have is that i had already done that before implementing this fix thingy in this thread and now it believes i havent done it despite the correct things have been changed like in the link you shared with me.

**Comment by Divergentcurl** [comment]
I don't know how to help you further with the information you have given me. Maybe you could make a backup of both addons and try again with a fresh install? If that doesn't work out you can always restore the backups.

**Comment by teelolws** [comment]
Mikanikos was "nerfed" in 9.2.5. Bugfix to match its actual tooltip. Spell 85 modDamageTaken from -5000 to -50

**Comment by solkarnar** [comment]
> Mikanikos was "nerfed" in 9.2.5. Bugfix to match its actual tooltip. Spell 85 modDamageTaken from -5000 to -50

[85]={type="aura", target=3, duration=2, firstTurn=3, modDamageTaken=**-50**},

This should be the new value in the vs-spells.lua file right?

**Comment by zeenk** [comment]
> [85]={type="aura", target=3, duration=2, firstTurn=3, modDamageTaken=**-50**},
> 
> This should be the new value in the vs-spells.lua file right?

Yes

**Comment by woefulwabbit** [comment]
@hythloday Are you able to add a few collaborators to the project e.g. @Divergentcurl @zealvurte so they can merge updates and create releases?

**Comment by Barleduq** [comment]
Adding to the request at least at the point of creating releases such that the CurseBreaker addon can pick it up automagically.  (Currently hitting 'code' button for more recent .zip file on Divergentcurl's fork, and installing it as instructed above, and hoping I'm doing all that needs doing.)

**Comment by Divergentcurl** [comment]
Thanks for reporting the Mikanikos change. I have updated my branch and have created a new [project](https://www.wowinterface.com/downloads/fileinfo.php?id=26347) on WOWInterface to make it easier for everyone to update.

**Comment by Barleduq** [comment]
Wow, thanks!  I've made a comment there for clarification, in case anyone just comes across it there and is confused.

**Comment by rewzone** [comment]
> Please have a look at https://github.com/Divergentcurl/VenturePlanSoDMissions/tree/cumulative-fixes#getting-it-running. It should help you get these fixes running. You only have to do this once.

I'm having an issue following your added instructions around overrideAA. That code doesn't seem to be in the vs.lua file for me. I also noticed I'm running 4.22 which is the current version of Venture Plan on Curse.

**Comment by greghudson** [comment]
With Venture Plan 4.22 you shouldn't need the fixes from this addon any longer.  (At least in my experience; I haven't failed a mission since I updated to 4.22.)
