### ISSUE TITLE
Change companion layout?

### ISSUE THREAD

**Issue by Rubyurek** [hythloday/VenturePlanSoDMissions#72]
Is it possible to fix the layout of the companions? I downloaded the fixed version but i don't have the new layout by ventureplan.

**Comment by solkarnar** [comment]
At renown level 62, you will gain your 21st companion. VenturePlan is coded to handle a maximum to 20 companions. You will start seeing errors about self.info being nil. To fix this, edit the file _retail_/Interface/AddOns/VenturePlan/Widgets.lua: change line 1960 (in version 4.16a) from for i=1,20 do to for i=1,99 do. This will add support up to 99 companions.

After completing this change, the code should look like this:

```
s.companions = {}
for i=1,99 do
    t = CreateObject("FollowerListButton", f, false)
    t:SetPoint("TOPLEFT", ((i-1)%4)*76+14, -math.floor((i-1)/4)*72-130)
    s.companions[i] = t
end
```
