### ISSUE TITLE
Adventure Campaign Progress

### ISSUE THREAD

**Issue by givmeafreknname** [hythloday/VenturePlanSoDMissions#76]
I've noticed when swapping covenants that the progress counter will add the 2 numbers, instead of keeping track of whatever current covenant you're in. So for example between my maxed out Night Fae and whatever I currently have in Venthyr, it says I'm at 37. Hope to get this fixed soon. Thank you.

**Comment by solkarnar** [comment]
Don't think it will be fixed when core functionality isn't broken. I got this bug too and it doesn't mess with the core function which is to make the missions a success.

**Comment by sirzooro** [comment]
This is bug in the WoW itself. Adventure Campaign Progress is stored as a currency with ID 1889. I was Kyrian, switched to Necrolords and returned to Kyrians. After I returned I noticed that Adventure Campaign Progress is displayed incorrectly.

You can use following command to get amount of this currency:
`/script print(C_CurrencyInfo.GetCurrencyInfo(1889).quantity)`
