### ISSUE TITLE
In the relase show only number.

### ISSUE THREAD

**Issue by czullo** [hythloday/VenturePlanSoDMissions#9]
In relase show only number, not whole name + number to avoid this situation:

![Zrzut ekranu 2021-07-18 054219](https://user-images.githubusercontent.com/13511496/126054942-3adb953e-a126-4794-8ab9-f2f9958c69a0.png)

**Comment by hythloday** [comment]
This is interesting - I don't see this, and it doesn't reflect the version in the toc. How did you install the addon?

**Comment by Mastecki** [comment]
Let me add some more info to it: Installed through wowup.io - install from url: got the same long version name, additionally, the game version is odd.
![Zrzut ekranu 2021-07-18 141013](https://user-images.githubusercontent.com/87605297/126066551-a4ffbd2f-1dc7-45ab-a8e5-dceed44377f3.png)

**Comment by czullo** [comment]
> This is interesting - I don't see this, and it doesn't reflect the version in the toc. How did you install the addon?

Selected install from ULR

**Comment by SoLoR1** [comment]
> Let me add some more info to it: Installed through wowup.io - install from url: got the same long version name, additionally, the game version is odd.

yeh there is minor error in toc with interface version, doesnt hurt anything but OCD :) also about this issue you are seeing, it only happens if you use github as a source, if you use wowinterface its fine.

**Comment by hythloday** [comment]
I've merged a PR that changed the ToC, let me know if that doesn't fix this.
